package co.fcv.citas.auth;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import static org.hamcrest.Matchers.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import com.fasterxml.jackson.databind.ObjectMapper; import co.fcv.citas.user.UserRepository; import org.springframework.security.crypto.password.PasswordEncoder;
@SpringBootTest @AutoConfigureMockMvc class AuthControllerTest { @Autowired MockMvc mvc; @Autowired ObjectMapper json; @Autowired UserRepository users; @Autowired PasswordEncoder encoder;
 private String registration(String email,String doc){return "{\"names\":\"Ana\",\"surnames\":\"Pérez\",\"documentType\":\"CC\",\"documentNumber\":\""+doc+"\",\"email\":\""+email+"\",\"phone\":\"3001234567\",\"password\":\"ClaveSegura123\"}";}
 @Test void registerCreatesUserAndDoesNotExposePassword() throws Exception {mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration("ana@test.local","1001"))).andExpect(status().isCreated()).andExpect(content().string(isEmptyString())); var saved=users.findByEmailIgnoreCase("ana@test.local").orElseThrow(); Assertions.assertNotEquals("ClaveSegura123",saved.getPasswordHash()); Assertions.assertTrue(encoder.matches("ClaveSegura123",saved.getPasswordHash()));}
 @Test void duplicateEmailAndDocumentAreRejected() throws Exception {mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration("dup@test.local","1002"))).andExpect(status().isCreated()); mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration("dup@test.local","1003"))).andExpect(status().isConflict()); mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration("other@test.local","1002"))).andExpect(status().isConflict());}
 @Test void loginReturnsAccessAndRefreshAndRefreshRotates() throws Exception {mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration("login@test.local","1004"))).andExpect(status().isCreated()); String body=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"login@test.local\",\"password\":\"ClaveSegura123\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.accessToken",not(emptyString()))).andExpect(jsonPath("$.refreshToken",not(emptyString()))).andReturn().getResponse().getContentAsString(); String refresh=json.readTree(body).get("refreshToken").asText(); String renewed=mvc.perform(post("/api/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+refresh+"\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.accessToken",not(emptyString()))).andReturn().getResponse().getContentAsString(); String rotated=json.readTree(renewed).get("refreshToken").asText(); Assertions.assertNotEquals(refresh,rotated); mvc.perform(post("/api/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+refresh+"\"}")).andExpect(status().isUnauthorized());}
 @Test void invalidCredentialsAndMalformedRefreshAreRejected() throws Exception {mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"missing@test.local\",\"password\":\"bad\"}")).andExpect(status().isUnauthorized()); mvc.perform(post("/api/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\"not-a-token\"}")).andExpect(status().isUnauthorized());}
}
