package co.fcv.citas.auth;
import co.fcv.citas.user.*; import co.fcv.citas.session.*; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class AuthService { private final UserRepository users; private final RefreshSessionRepository sessions; private final PasswordEncoder encoder; private final JwtService jwt; private final int refreshDays;
 public AuthService(UserRepository u,RefreshSessionRepository s,PasswordEncoder e,JwtService j,org.springframework.core.env.Environment env){users=u;sessions=s;encoder=e;jwt=j;refreshDays=Integer.parseInt(env.getProperty("app.jwt.refresh-days","7"));}
 @Transactional public User register(RegisterRequest r){String email=r.email().trim().toLowerCase(Locale.ROOT); if(users.existsByEmailIgnoreCase(email)||users.existsByDocumentTypeAndDocumentNumber(r.documentType().trim(),r.documentNumber().trim())) throw new ResponseStatusException(HttpStatus.CONFLICT,"email o documento ya registrado"); return users.save(new User(r.names().trim(),r.surnames().trim(),r.documentType().trim(),r.documentNumber().trim(),email,r.phone().trim(),encoder.encode(r.password())));}
 @Transactional public TokenResponse login(LoginRequest r){User u=users.findByEmailIgnoreCase(r.email()).filter(User::isActive).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"credenciales inválidas")); if(!encoder.matches(r.password(),u.getPasswordHash())) throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"credenciales inválidas"); return issue(u);}
 @Transactional public TokenResponse refresh(String raw){RefreshSession old=sessions.findByTokenHash(hash(raw)).filter(s->!s.isRevoked()&&s.getExpiresAt().isAfter(Instant.now())).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"refresh inválido")); old.revoke(); User u=users.findById(old.getUserId()).filter(User::isActive).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"refresh inválido")); return issue(u);}
 @Transactional public void logout(String raw){sessions.findByTokenHash(hash(raw)).ifPresent(RefreshSession::revoke);}
 private TokenResponse issue(User u){String access=jwt.access(u); String refresh=jwt.refresh(u); sessions.save(new RefreshSession(u.getId(),hash(refresh),Instant.now().plus(refreshDays, java.time.temporal.ChronoUnit.DAYS))); return new TokenResponse(access,refresh,"Bearer",jwt.accessSeconds());}
 static String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 public record RegisterRequest(String names,String surnames,String documentType,String documentNumber,String email,String phone,String password){} public record LoginRequest(String email,String password){} public record TokenResponse(String accessToken,String refreshToken,String tokenType,long expiresIn){}
}
