package co.fcv.citas.appointment;

import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.jdbc.support.GeneratedKeyHolder; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.security.core.Authentication;

@RestController @RequestMapping("/api/v1/appointments")
public class AppointmentBookingController {
  private final JdbcTemplate db; public AppointmentBookingController(JdbcTemplate db){this.db=db;}
  @PostMapping("/general") @Transactional ResponseEntity<?> general(@RequestBody Booking r,Authentication a){return book(r,a,"APPROVED",true);}
  @PostMapping("/specialized") @Transactional ResponseEntity<?> specialized(@RequestBody Booking r,Authentication a){return book(r,a,"REQUESTED",false);}
  private ResponseEntity<?> book(Booking r,Authentication a,String status,boolean general){ if(r==null||r.slotId()==null||r.specialtyId()==null)return bad("datos incompletos"); long patient=Long.parseLong(a.getName()); Integer duration=db.queryForObject("SELECT appointment_duration_minutes FROM specialties WHERE id=? AND active=TRUE AND is_general=?",Integer.class,r.specialtyId(),general); if(duration==null)return bad("especialidad no elegible"); var slots=db.queryForList("SELECT ps.id,ps.start_at,ps.end_at,ab.professional_id,ab.location_id FROM professional_slots ps JOIN availability_blocks ab ON ab.id=ps.availability_block_id JOIN professional_specialties psp ON psp.professional_id=ab.professional_id AND psp.specialty_id=? AND psp.active=TRUE JOIN professionals p ON p.id=ab.professional_id AND p.active=TRUE WHERE ps.id=? AND ps.appointment_id IS NULL",r.specialtyId(),r.slotId()); if(slots.isEmpty())return conflict("franja no disponible"); var s=slots.get(0); long pro=((Number)s.get("professional_id")).longValue(); long loc=((Number)s.get("location_id")).longValue(); var rawStart=s.get("start_at"); var start=rawStart instanceof java.sql.Timestamp t?t.toLocalDateTime():(java.time.LocalDateTime)rawStart; var end=start.plusMinutes(duration); int needed=duration/30; int free=db.queryForObject("SELECT COUNT(*) FROM professional_slots ps JOIN availability_blocks ab ON ab.id=ps.availability_block_id WHERE ab.professional_id=? AND ab.location_id=? AND ps.start_at>=? AND ps.start_at<? AND ps.appointment_id IS NULL",Integer.class,pro,loc,start,end); if(free!=needed)return conflict("franja no disponible"); Integer statusId=db.queryForObject("SELECT id FROM appointment_statuses WHERE code=?",Integer.class,status); var key=new GeneratedKeyHolder(); db.update(c->{var p=c.prepareStatement("INSERT INTO appointments(patient_user_id,professional_id,location_id,specialty_id,status_id,scheduled_start_at,scheduled_end_at,created_by_user_id) VALUES(?,?,?,?,?,?,?,?)",java.sql.Statement.RETURN_GENERATED_KEYS);p.setLong(1,patient);p.setLong(2,pro);p.setLong(3,loc);p.setLong(4,r.specialtyId());p.setInt(5,statusId);p.setObject(6,start);p.setObject(7,end);p.setLong(8,patient);return p;},key); long appointment=key.getKey().longValue(); int claimed=db.update("UPDATE professional_slots ps JOIN availability_blocks ab ON ab.id=ps.availability_block_id SET ps.appointment_id=? WHERE ab.professional_id=? AND ab.location_id=? AND ps.start_at>=? AND ps.start_at<? AND ps.appointment_id IS NULL",appointment,pro,loc,start,end); if(claimed!=needed)throw new IllegalStateException("conflicto de concurrencia"); return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("id",appointment,"status",status,"startAt",start,"endAt",end,"professionalId",pro,"locationId",loc,"specialtyId",r.specialtyId())); }
  private ResponseEntity<Map<String,String>> bad(String m){return ResponseEntity.badRequest().body(Map.of("message",m));} private ResponseEntity<Map<String,String>> conflict(String m){return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("message",m));}
  record Booking(Long slotId,Long specialtyId){}
}
